# Generated by Django 3.2.4 on 2021-08-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyweb', '0005_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
